### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by JimmyLefrancois** [getgrav/grav-skeleton-soraarticle-blog#1]
Hi guys!

I really dont understand how to start Grav with this skeleton! It contain just the /user folder, how Grav can works only with this files?

You say :

> A skeleton package is great way to get started with Grav. They are an all-in-one package containing the core Grav system plus sample pages, plugins, configuration etc. Simply download the ZIP file, extract it in your web-root, and your done!

I follow this step, but in my case i'm not done! Have you an idea?

Thank you guys!

**Comment by rhukster** [comment]
Two options:

1) download the zip from http://getgrav.org/downloads/skeletons, extract it, done.
2) download an extract thel regular Grav Core zip.  Remove `user/` folder.  Git clone this project as `user/`, then run `bin/grav install`. done
