### ISSUE TITLE
Remote http sideloading on https-sites

### ISSUE THREAD

**Issue by Gabbalo** [getgrav/grav-skeleton-soraarticle-blog#3]
The theme loads insecure content even if hosted under https.
As far as I can tell those things are 

font: Merriweather from Googleapis 
form: Arvo Regular from Googleapis
translate widged: from Google
mailverify: from google
css: background-picture from blogspot (style.css L. 2711)
css: gplus icon from gstatic (widget_css_2_bundle.css)
css: blogger.com icon  (widget_css_2_bundle.css) (two times)
Probably more ...

I am pretty sure, all ressources provide https by themself. 
If I will have time this weekend, I will check the code for those snippits myself if a 'fix' is not provided until then. The security-warning is by now the only flaw in this awesom theme :)

**Comment by hexplor** [comment]
This is theme issue. Fixed in develop channel. Thanks :)
