### ISSUE TITLE
Customize the appearance

### ISSUE THREAD

**Issue by sebastianwr** [getgrav/grav-skeleton-soraarticle-blog#7]
Hi,

is there some kind of best practice on how to customise the theme? E.g. I would like to remove the master slider, change fonts and the sidebar content.

Editing the theme directly would probably break updates in the future so I thought it might be wiser to edit this in the user directory but I am not sure how.

Kind regards,
Sebastian

**Comment by flaviocopes** [comment]
Hi, the way to go is creating a child theme: https://learn.getgrav.org/themes/customization#theme-inheritance
